# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7dfeae75f23cc7b70e9d18b97a23216b68f0b7c47a2a671163338b5c9246c60aa643d72b592ce9c1b0e94245d72bbef4359ea2cb80879a64efc23ab3fbfe3d2c

test:
  secret_key_base: 8e9c8e4c90bfd353ae7b906debffcbff24f254b3fc2c3079b9fca06835e32c4a4285ce76ac9927510fb7bd7ca6ee4c295c0de5a8b1cb4769f8c00e22a428a788

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
